// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANa50T_GpAVXx4SQEsnU52aO72Ma529_I',
    appId: '1:293388346215:web:5853aad1fd46dd635185c2',
    messagingSenderId: '293388346215',
    projectId: 'flashai-99601',
    authDomain: 'flashai-99601.firebaseapp.com',
    storageBucket: 'flashai-99601.firebasestorage.app',
    measurementId: 'G-RSFT3MV2VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEou3oB6oQINtBJs4J0HjV5ndGfzMoW_M',
    appId: '1:293388346215:android:dea864778f13ada45185c2',
    messagingSenderId: '293388346215',
    projectId: 'flashai-99601',
    storageBucket: 'flashai-99601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZGpi0KCkdPobvKDBXB_dAJYND-tNx2Ow',
    appId: '1:293388346215:ios:d92b4d58f012cad95185c2',
    messagingSenderId: '293388346215',
    projectId: 'flashai-99601',
    storageBucket: 'flashai-99601.firebasestorage.app',
    iosBundleId: 'com.example.flashai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZGpi0KCkdPobvKDBXB_dAJYND-tNx2Ow',
    appId: '1:293388346215:ios:d92b4d58f012cad95185c2',
    messagingSenderId: '293388346215',
    projectId: 'flashai-99601',
    storageBucket: 'flashai-99601.firebasestorage.app',
    iosBundleId: 'com.example.flashai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANa50T_GpAVXx4SQEsnU52aO72Ma529_I',
    appId: '1:293388346215:web:c6032a5f1fad0e3e5185c2',
    messagingSenderId: '293388346215',
    projectId: 'flashai-99601',
    authDomain: 'flashai-99601.firebaseapp.com',
    storageBucket: 'flashai-99601.firebasestorage.app',
    measurementId: 'G-3T6MMT5J09',
  );
}
